# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Layers < Formula
  desc "Layers CLI - Command line interface for Layers"
  homepage "https://layers.com"
  version "2.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/layers/cli/releases/download/v2.1.7/layers_2.1.7_darwin_amd64.tar.gz"
      sha256 "4550fd0a421a5d4c92e19b5d5cf25339a09e51d9107c95e67e2d6b36347c46db"

      define_method(:install) do
        bin.install "layers"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/layers/cli/releases/download/v2.1.7/layers_2.1.7_darwin_arm64.tar.gz"
      sha256 "e6f749dec557942bc0d9a964f63c5dbe7db9be72314dbd7df298821ab4fbf11a"

      define_method(:install) do
        bin.install "layers"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/layers/cli/releases/download/v2.1.7/layers_2.1.7_linux_amd64.tar.gz"
      sha256 "3afe10a6def3041bd4add5b524c39d73b942142435e9453c4079aae3aad76e7a"
      define_method(:install) do
        bin.install "layers"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/layers/cli/releases/download/v2.1.7/layers_2.1.7_linux_arm64.tar.gz"
      sha256 "530e600fb8659c5e3feca25e9438af21ddf1a5738f4b0a5f9bb41c0df933bf8b"
      define_method(:install) do
        bin.install "layers"
      end
    end
  end

  test do
    system "#{bin}/layers", "version"
  end
end
