# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Layers < Formula
  desc "Layers CLI - Command line interface for Layers"
  homepage "https://layers.com"
  version "2.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/layers/cli/releases/download/v2.1.9/layers_2.1.9_darwin_amd64.tar.gz"
      sha256 "3fcdd49e90daa2f9bd68064fcc416c89e851c9b95a6050031c3a80f6a14716ce"

      define_method(:install) do
        bin.install "layers"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/layers/cli/releases/download/v2.1.9/layers_2.1.9_darwin_arm64.tar.gz"
      sha256 "263cda9452af06fd606bb2fc8206117574d55af11b2c302accb14a0f33c7f24b"

      define_method(:install) do
        bin.install "layers"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/layers/cli/releases/download/v2.1.9/layers_2.1.9_linux_amd64.tar.gz"
      sha256 "21c5e0a33abf7ce0eaf31738bcfbcceb597a20ec5720aaabadfd6dc7923a87ba"
      define_method(:install) do
        bin.install "layers"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/layers/cli/releases/download/v2.1.9/layers_2.1.9_linux_arm64.tar.gz"
      sha256 "8137583ae622902e537764d4dab3b4f41996227df2971eaa101814b1424402c2"
      define_method(:install) do
        bin.install "layers"
      end
    end
  end

  test do
    system "#{bin}/layers", "version"
  end
end
